version = 1

[install]
go.pkg-path = "go"
gnumake.pkg-path = "gnumake"

[build.noxdir]

command = "make build; mkdir -p $out/bin; cp bin/noxdir $out/bin"
description = "Terminal utility for visualizing file system usage."
version = "v0.1.3"


[options]
# Systems that environment is compatible with
systems = [
  "aarch64-darwin",
  "aarch64-linux",
  "x86_64-darwin",
  "x86_64-linux",
]
