version = 1

[install]
go.pkg-path = "go"

[build.noxdir]
command = "mkdir -p $out/bin && go build -trimpath . ; mv noxdir $out/bin/noxdir"
version = "v0.1.3"
description = "noxdir is a storage visualization tool for the CLI on Mac or Linux"

[options]
# Systems that environment is compatible with
systems = [
  "aarch64-darwin",
  "aarch64-linux",
  "x86_64-darwin",
  "x86_64-linux",
]
